# Generated by Django 3.1.4 on 2020-12-28 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(blank=True, max_length=100, null=True)),
                ('search_date', models.DateField(blank=True, null=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TvSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('search_term', models.ManyToManyField(blank=True, to='tvseries.SearchTerm')),
            ],
        ),
    ]
