# Generated by Django 3.1.4 on 2020-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
